version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my_network


  backend:
    build:
      context: .
      args:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_HOST=db
    restart: always

    command: >
      bash -c "sleep 10 &&
      alembic revision --autogenerate -m 'initial' &&
      alembic upgrade head &&
      python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8080:8000"
    depends_on:
      - db
    networks:
      - my_network
volumes:
  postgres_data:
    driver: local


networks:
  my_network:
    driver: bridge
