"""empty message

Revision ID: 2e251c5a7e2b
Revises: 3bafbf0b5357
Create Date: 2024-07-07 00:58:09.500389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e251c5a7e2b'
down_revision: Union[str, None] = '3bafbf0b5357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_statistic_fkey', 'camera', type_='foreignkey')
    op.drop_column('camera', 'statistic')
    op.add_column('statistic', sa.Column('camera_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'statistic', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistic', type_='foreignkey')
    op.drop_column('statistic', 'camera_id')
    op.add_column('camera', sa.Column('statistic', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('camera_statistic_fkey', 'camera', 'statistic', ['statistic'], ['id'])
    # ### end Alembic commands ###
