"""empty message

Revision ID: b3599e7ebba3
Revises: 2e251c5a7e2b
Create Date: 2024-07-07 01:13:30.838023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3599e7ebba3'
down_revision: Union[str, None] = '2e251c5a7e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('car_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'report', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'car_id')
    # ### end Alembic commands ###
